"""Renders a completed session into a physician-facing PDF.

HTML/CSS -> PDF, not hand-built flowables: `templates/report.html.j2` (a
Jinja2 template) is the one source of layout and colour for every report --
each session supplies its own values, and a section that has nothing to
show (no medications, no additional notes, no findings at all) renders its
"None reported" placeholder or, for the optional trailing sections, omits
itself entirely via the template's own `{% if %}` guards. That is what
makes "only show what this session actually has" a template concern
instead of a page-count calculation: the same template handles a bare
routine-checkup session and a session with every field populated, and
Chromium paginates wherever the content actually runs out of room.

Rendered by headless Chromium (Playwright), deliberately not WeasyPrint:
WeasyPrint needs Pango/Cairo/GTK installed on the host, a real liability on
Windows dev machines and a fragile system dependency in the Docker image.
Playwright bundles its own Chromium build, so the only install step is
`playwright install chromium` -- no system graphics stack either place.
This replaces an earlier ReportLab implementation (pure-Python flowables,
one `Table`/`TableStyle` call per box) that could not reasonably produce
this design's coloured section bands and grid layout -- CSS grid/flexbox
express that layout directly; ReportLab's flowable model does not have an
equivalent without hand-computing every column width.

Every patient- or LLM-derived string reaches the template unescaped in
Python and is escaped by Jinja2's own autoescaping (see `_ENVIRONMENT`
below) before it lands in the HTML -- the same protection `_xml_escape`
gave ReportLab's paragraph markup, applied automatically instead of at
every call site.
"""

import base64
from dataclasses import dataclass
from datetime import UTC, date, datetime
from io import BytesIO
from pathlib import Path
from zoneinfo import ZoneInfo

from jinja2 import Environment, FileSystemLoader, select_autoescape
from markupsafe import Markup
from playwright.sync_api import sync_playwright
from pypdf import PdfReader, PdfWriter

from app.agents.summarizer.agent import DESCRIPTION_UNAVAILABLE
from app.core.constants import prescreening_category_label
from app.models.report import SocialHistory
from app.models.session import Session

_TEMPLATES_DIR = Path(__file__).parent / "templates"
_ENVIRONMENT = Environment(
    loader=FileSystemLoader(_TEMPLATES_DIR),
    # Autoescapes every interpolated value as HTML -- a patient's own words
    # containing "<" or "&" must render as literal text, never as markup.
    autoescape=select_autoescape(enabled_extensions=("j2", "html")),
)
_TEMPLATE = _ENVIRONMENT.get_template("report.html.j2")


def _load_font_face_css() -> Markup:
    """Build the `@font-face` block embedding DM Sans -- the same typeface
    `--font-sans` names in the patient app's own `theme.css` -- as inline
    base64 `data:` URIs.

    Embedded, not linked to Google Fonts: report rendering must not depend
    on outbound network access from inside the container at render time,
    and a `@font-face` `url()` pointing at `fonts.gstatic.com` would make
    every report generation a hostage to that request succeeding. Both
    files are Google's actual variable-font builds (weight axis 100-1000),
    so `font-weight: 400/500/600/700` in the stylesheet below each resolve
    to a real instance of the one file rather than being faked with CSS
    `font-weight` on a static face.
    """
    fonts_dir = _TEMPLATES_DIR / "fonts"
    normal_b64 = base64.b64encode((fonts_dir / "DMSans-Variable.woff2").read_bytes()).decode()
    italic_b64 = base64.b64encode(
        (fonts_dir / "DMSans-Variable-Italic.woff2").read_bytes()
    ).decode()
    return Markup(
        "@font-face {"
        "font-family:'DM Sans';font-style:normal;font-weight:400 900;font-display:swap;"
        f"src:url(data:font/woff2;base64,{normal_b64}) format('woff2');"
        "}"
        "@font-face {"
        "font-family:'DM Sans';font-style:italic;font-weight:400 900;font-display:swap;"
        f"src:url(data:font/woff2;base64,{italic_b64}) format('woff2');"
        "}"
    )


_FONT_FACE_CSS = _load_font_face_css()
"""Built once at import time -- the font files never change, so re-reading
and re-encoding them on every report would be pure waste."""

_DISCLAIMER = (
    "Generated by an AI pre-consultation assistant from patient-reported responses. "
    "Not a diagnosis, triage decision, or treatment recommendation."
)

_FOOTER_TEMPLATE = """
<div style="font-size:8px;color:#6b6b6b;width:100%;padding:0 13mm;
display:flex;justify-content:space-between;font-family:Helvetica,Arial,sans-serif;">
  <span>CONFIDENTIAL &mdash; for clinician review only</span>
  <span><span class="pageNumber"></span> / <span class="totalPages"></span></span>
</div>
"""
"""Playwright renders this as a real page footer (outside the page's own
HTML), so every page gets "Page X of Y" without the two-pass buffering
canvas trick the ReportLab version needed for the same result."""


@dataclass(frozen=True)
class DocumentAttachment:
    """A patient-uploaded supporting file to embed inside the report PDF
    itself, as opposed to `document_download_url`'s plain link.

    Deliberately separate from the link: generating this means downloading
    the file's actual bytes from object storage, a slower and more
    failure-prone step than presigning a URL, so callers may supply
    either, both, or neither depending on what they can afford.
    """

    filename: str
    data: bytes
    content_type: str


def _age_years(date_of_birth: date, as_of: date) -> int:
    """Whole years elapsed, not just a year subtraction -- a patient born
    29 Sep isn't yet the later age on a report generated in early Sep."""
    had_birthday_this_year = (as_of.month, as_of.day) >= (date_of_birth.month, date_of_birth.day)
    return as_of.year - date_of_birth.year - (0 if had_birthday_this_year else 1)


def _format_appointment(session: Session) -> str:
    """Converted to the clinic's local zone and labeled (`%Z`), mirroring
    `generated_at`'s own UTC label below -- an unlabeled clinical
    timestamp a physician acts on is a defect in its own right, and a
    bare UTC `strftime` here used to show the wrong hour whenever the
    clinic isn't in UTC. Pure and extracted specifically so this is
    unit-testable independent of full PDF rendering."""
    local = session.appointment_datetime.astimezone(ZoneInfo(session.appointment_timezone))
    return local.strftime("%a %d %b %Y, %H:%M %Z")


def _social_history_lines(social: SocialHistory) -> list[str]:
    """Only the social-history entries the patient actually answered.

    An unanswered field is omitted rather than rendered as "not stated"
    beside three real values: the physician should see the gap in the
    report's own gaps section, not read four rows where only one is real.
    """
    labelled = (
        ("Tobacco", social.tobacco_use),
        ("Alcohol", social.alcohol_use),
        ("Occupation", social.occupation),
        ("Living situation", social.living_situation),
    )
    return [f"{label}: {value}" for label, value in labelled if value]


def _document_description(session: Session) -> tuple[str, bool] | None:
    """What the attached document is, and whether the patient said so.

    Two sources, and the patient's own words come first. `describe_document`
    is bound to state the document's *modality only* -- it is forbidden from
    naming anything inside the file -- so at its very best it produces "a lab
    report" where the patient has already told the call "CBC report". It also
    fails outright more often than it should: an iPhone photo uploads as
    `image/heic`, which the browser accepts and Bedrock cannot read at all,
    and every one of those resolves to `DESCRIPTION_UNAVAILABLE`.

    So the answer to "what is this attachment" is the answer the patient
    gave when asked, recorded on `recent_tests`. The automatic description
    is the fallback, and the flag is what lets the page attribute each
    honestly rather than presenting a model's guess as the patient's word.
    """
    report = session.report
    reported = (report.recent_tests or "").strip() if report is not None else ""
    if reported:
        return reported, True

    described = (session.document_summary or "").strip()
    if described and described != DESCRIPTION_UNAVAILABLE:
        return described, False
    return None


def render_report_html(session: Session, document_download_url: str | None = None) -> str:
    """Build the report's HTML, without printing it.

    Split out from `render_report_pdf` so the layout can be asserted on
    directly. Going through Chromium to check that a field has an icon
    beside it means asserting on a PDF byte stream, which is why the
    template's structure had no tests at all.

    Raises `ValueError` if `session.report` is not set.
    """
    if session.report is None:
        raise ValueError(f"Session {session.session_id!r} has no report to render")
    report = session.report

    category_label = (
        prescreening_category_label(report.category) if report.category else "General intake"
    )
    return _TEMPLATE.render(
        font_face_css=_FONT_FACE_CSS,
        patient_name=session.patient.name,
        patient_age=_age_years(session.patient.date_of_birth.date(), datetime.now(UTC).date()),
        patient_sex=session.patient.sex.value.capitalize(),
        patient_dob=session.patient.date_of_birth.strftime("%d %b %Y"),
        patient_phone=session.patient.contact_phone,
        physician=session.physician,
        appointment=_format_appointment(session),
        generated_at=datetime.now(UTC).strftime("%d %B %Y, %H:%M UTC"),
        session_id=session.session_id,
        document_download_url=document_download_url,
        category_label=category_label,
        chief_concern=report.chief_concern,
        clinical_summary=report.clinical_summary,
        flagged=[f for f in report.findings if f.flagged],
        medications=report.medications,
        allergies=report.allergies,
        ongoing_conditions=report.ongoing_conditions,
        hospital_stays=report.hospital_stays,
        recent_care=report.recent_care,
        recent_tests=report.recent_tests,
        family_history=report.family_history,
        social_history_lines=_social_history_lines(report.social_history),
        patient_goal=report.patient_goal,
        additional_notes=report.additional_notes,
        document_uploaded=session.document_uploaded,
        document_description=_document_description(session),
        gaps=report.gaps,
        findings=report.findings,
        disclaimer=_DISCLAIMER,
    )


def render_report_pdf(
    session: Session,
    document_download_url: str | None = None,
    attachment: DocumentAttachment | None = None,
) -> bytes:
    """Build the physician PDF for a session with a completed report.

    `document_download_url`, when given, is a presigned link to a
    patient-uploaded supporting document, rendered as a clickable line in
    both the identity card and the "Attached documents" section.
    `attachment`, when given, additionally embeds that same file's actual
    bytes inside the PDF (see `DocumentAttachment`) -- generating it is a
    network call, so both are built by the async caller
    (`SessionService`), never here; this function stays a synchronous
    renderer, run off the event loop via `asyncio.to_thread` by its caller
    the same way this codebase already runs every other blocking call
    (boto3, `ObjectStorageClient`).

    Raises `ValueError` if `session.report` is not set; callers only reach
    this once summarization has succeeded.
    """
    pdf_bytes = _html_to_pdf(render_report_html(session, document_download_url))
    if attachment is not None:
        pdf_bytes = _embed_attachment(pdf_bytes, attachment)
    return pdf_bytes


def _html_to_pdf(html: str) -> bytes:
    """Print the rendered HTML to PDF bytes via headless Chromium.

    A fresh browser per call, not a shared/pooled one: report generation
    is low-frequency (once per completed session) and this stays the
    simplest correct thing -- pooling a browser process across requests
    is a real optimization but not one this volume needs yet.
    """
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch()
        try:
            page = browser.new_page()
            page.set_content(html)
            return page.pdf(
                format="A4",
                print_background=True,
                display_header_footer=True,
                header_template="<div></div>",
                footer_template=_FOOTER_TEMPLATE,
                # One margin system, not two: the template itself carries no
                # page padding, so this is the only place page margins are
                # set -- a previous version split the margin between this
                # and the template's own `.page` padding, which made the
                # actual whitespace hard to reason about and to tune.
                margin={"top": "11mm", "bottom": "16mm", "left": "13mm", "right": "13mm"},
            )
        finally:
            browser.close()


def _embed_attachment(pdf_bytes: bytes, attachment: DocumentAttachment) -> bytes:
    """Embed the patient's uploaded file inside the report PDF itself.

    Adds it as an embedded file (the "paperclip" attachment a PDF viewer
    lists), not a page merge -- the upload is not guaranteed to be a PDF
    (an X-ray JPEG, a scanned referral, a lab PDF), so this one mechanism
    covers every type with no per-type conversion step.
    """
    reader = PdfReader(BytesIO(pdf_bytes))
    writer = PdfWriter()
    writer.append(reader)
    writer.add_attachment(attachment.filename, attachment.data)
    out = BytesIO()
    writer.write(out)
    return out.getvalue()
