"""Write `contracts/intake-field-options.json` from the backend registry.

The backend owns `SCREEN_FIELD_OPTIONS` because it is the layer that has
to *refuse* an id the model invents. The frontend owns the option lists
the patient actually sees, complete with icons and copy. Those are two
different concerns over one vocabulary, so the vocabulary is exported here
and asserted on both sides:

    python scripts/export_field_options.py

`tests/unit/test_field_option_contract.py` fails if this file is stale, and
the UI's `intakeFieldOptions.test.ts` fails if its own option lists have
drifted from it. Adding an option is therefore a three-line change that
cannot be half-done.
"""

import json
from pathlib import Path

from app.core.constants import SCREEN_FIELD_OPTIONS, SCREEN_FIELDS

CONTRACT_PATH = Path(__file__).resolve().parents[2] / "contracts" / "intake-field-options.json"


def build() -> dict[str, object]:
    """The vocabulary, plus which screen each field belongs to."""
    screen_of = {
        field: screen.value for screen, fields in SCREEN_FIELDS.items() for field in fields
    }
    return {
        "_comment": (
            "Generated by prescreening-agent-api/scripts/export_field_options.py. "
            "Do not edit by hand -- edit SCREEN_FIELD_OPTIONS in "
            "app/core/constants.py and re-run it."
        ),
        "fields": {
            field: {"screen": screen_of[field], "options": list(options)}
            for field, options in SCREEN_FIELD_OPTIONS.items()
        },
    }


def main() -> None:
    CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTRACT_PATH.write_text(json.dumps(build(), indent=2) + "\n", encoding="utf-8")
    print(f"wrote {CONTRACT_PATH}")


if __name__ == "__main__":
    main()
